package com.changhong.wifimng.ui.fragment;

public enum EnumPage {

    ROUTER_SETTING,
    NET_MENU,
    WIZARD_FIRST,
    WIFI_SETTING, WIFI_SETTING_ADVANCE,
    WAN_SETTING,
    ADMIN_PASSWORD,
    LAN_SETTING,
    GUEST_NETWORK,
    ADD_MESH,
    WLAN_ACCESS,
    ROUTER_DEVICE_INFO,
    SPEED_LIMIT,
    DDNS_SHOW,
    DDNS_ADDED,
    DEVICE_UPDATE,
    ACCESS_LIST,
    GROUP_SETTING,
    DEVICE_SHARE,
    DEVICE_NAME_AND_ROOM,
    TEST_INTERNET_TIME_LIMIT_LIST,
    TEST_SPEED_LIMIT_LIST
}
